#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const abbrev = require('abbrev');

const stdout = process.stdout;

fs.readdir(path.join(__dirname, "/command"), function(err, items) {
    if (err) {
        return stdout.write("Unable to list commands\n");
    }

    let commands = items
        .filter((item) => path.extname(item) == '.js' ? true : false)
        .map((item) => path.basename(item, '.js'))

    let command = abbrev.apply(abbrev, commands)[process.argv[2]];
    let commandPath = path.join(__dirname, "command", command + '.js');

    fs.exists(commandPath, (exists) => {
        if (exists) {
            return require(commandPath)(stdout);
        }

        stdout.write(`Unable to locate command: ${process.argv[2]}\n\n`);

        commands
            .map((item) => stdout.write(`  * ${item}\n`));

        stdout.write("\nUse per command `--help` for more information\n");
    });
});
